# Tarea - Programación lineal

In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from scipy import optimize as opt


### Diseño de la Dieta Óptima

Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de analisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estandares nutricionales. Los requisitos que se tienen es que en $100$ gramos, se deben tener **por lo menos** $8$ gramos de proteína y $6$ gramos de grasa. Así mismo, no se debe tener más de $2$ gramos de fibra y $0.4$ gramos de sal.  

Los datos nutricionales se pueden obtener de la siguiente tabla:

Ingrediente|Proteína|Grasa|Fibra|Sal
:----|----|----|----|----
Pollo|  10.0%|08.0%|00.1%|00.2%
Carne|  20.0%|10.0%|00.5%|00.5%
Cordero|15.0%|11.0%|00.5%|00.7%
Arroz|  00.0%|01.0%|10.0%|00.2%
Trigo|  04.0%|01.0%|15.0%|00.8%
Gel|    00.0%|00.0%|00.0%|00.0%

Los costos de cada producto son:

Ingrediente|Costo por gramo
:----|----
Pollo|$\$$0.013
Carne|$\$$0.008
Cordero|$\$$0.010
Arroz|$\$$0.002
Trigo|$\$$0.005
Gel|$\$$0.001    

Lo que se busca optimizar en este caso es la cantidad de productos que se debe utilizar en la comida de gato, minimizando el costo total. Para simplificar la notación use las siguientes variables: 

+ $x_1:$ Gramos de pollo  
+ $x_2:$ Gramos de carne  
+ $x_3:$ Gramos de cordero  
+ $x_4:$ Gramos de arroz  
+ $x_5:$ Gramos de trigo  
+ $x_6:$ Gramos de gel

La tarea consiste en plantear el problemade programación lineal que permita satisfacer las necesidades alimenticias del gato al tiempo que minimice el costo total y resolverlo con `linprog`.

Lo que se busca optimizar en este caso es la cantidad de productos que se debe utilizar en la comida de gato, para simplificar la notación se van a nombrar las siguientes variables:

𝑥1:
Gramos de pollo
𝑥2: Gramos de carne
𝑥3: Gramos de cordero
𝑥4: Gramos de arroz
𝑥5: Gramos de trigo
𝑥6:

Gramos de gel

Con los datos, se puede plantear la función objetivo, está dada por la siguiente expresión:

min0.013𝑥1+0.008𝑥2+0.010𝑥3+0.002𝑥4+0.005𝑥5+0.001𝑥6

Las restricciones estarían dadas por el siguiente conjunto de ecuaciones:

𝑥1+𝑥2+𝑥3+𝑥4+𝑥5+𝑥6=100

(10.0𝑥1+20.0𝑥2+15.0𝑥3+00.0𝑥4+04.0𝑥5+00.0𝑥6)/100≥8.0

(08.0𝑥1+10.0𝑥2+11.0𝑥3+01.0𝑥4+01.0𝑥5+00.0𝑥6)/100≥6.0

(00.1𝑥1+00.5𝑥2+00.5𝑥3+10.0𝑥4+15.0𝑥5+00.0𝑥6)/100≤2.0

(00.2𝑥1+00.5𝑥2+00.7𝑥3+00.2𝑥4+00.8𝑥5+00.0𝑥6)/100≤0.4

La primer condición asegura que la cantidad de productos que se usará cumple con los 100 gramos. Las siguientes sólo siguen los lineamientos planteados para cumplir con los requisitos nutrimentales. 

In [130]:
# Matrices y cotas
c = np.array([0.013,0.008,0.010,0.002,0.005,0.001])

A_ineq = np.array([[1,1,1,1,1,1],
                 [-0.1,-0.2,-0.15,0,-0.04,0],
                 [-0.08,-0.1,-0.11,-0.01,-0.01,0],
                 [0.0001,0.005,0.005,0.1,0.15,0],
                 [0.002,0.005,0.007,0.002,0.008,0]])

b_ineq = np.array([100,-8,-6,2,0.4])

# bnds = ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None))
bnds = ((0, None),) * 6

In [131]:
sol  = opt.linprog(c=c, A_ub=A_ineq, b_ub=b_ineq, bounds=bnds)
sol

     con: array([], dtype=float64)
     fun: 0.480000022781727
 message: 'Optimization terminated successfully.'
     nit: 7
   slack: array([3.99999970e+01, 3.99999979e+00, 1.17804777e-07, 1.69999993e+00,
       9.99999819e-02])
  status: 0
 success: True
       x: array([3.04269434e-07, 5.99999940e+01, 6.24482886e-06, 2.32315522e-08,
       4.54207387e-07, 1.91982301e-06])

In [132]:
opt.linprog(c=c, A_ub=A_ineq, b_ub=b_ineq)

     con: array([], dtype=float64)
     fun: 0.480000022781727
 message: 'Optimization terminated successfully.'
     nit: 7
   slack: array([3.99999970e+01, 3.99999979e+00, 1.17804777e-07, 1.69999993e+00,
       9.99999819e-02])
  status: 0
 success: True
       x: array([3.04269434e-07, 5.99999940e+01, 6.24482886e-06, 2.32315522e-08,
       4.54207387e-07, 1.91982301e-06])

In [133]:
x_min = sol.x
np.round(x_min)

array([ 0., 60.,  0.,  0.,  0.,  0.])

In [128]:
c

array([0.013, 0.008, 0.01 , 0.002, 0.005, 0.001])

In [134]:
c.T.dot(x_min)

0.480000022781727

### Problema de distribución de energía eléctrica

La Comisión Federal de Electricidad **(CFE)** dispone de cuatro plantas de generación para satisfacer la demanda diaria eléctrica en cuatro ciudades, Guadalajara, León y Morelia. Las plantas $1$, $2$ y $3$ pueden satisfacer $80$, $40$ y $60$ millones de KW al día respectivamente. Las necesidades de las ciudades de Guadalajara, León y Morelia son de $70$, $40$ y $70$ millones de Kw al día respectivamente. 


Los costos asociados al envío de suministro energético por cada millón de Kw entre cada planta y cada ciudad son los registrados en la siguiente tabla. 

-|Guadalajara|León|Morelia
:----|----|----|----
Planta 1|5|2|7
Planta 2|3|6|6
Planta 3|6|1|2

Y por último, las restricciones del problema, van a estar dadas por las capacidades de oferta y demanda de cada planta (en millones de KW) y cada ciudad.

Para simplificar la notación use las siguientes variables:

+ $x_1$: Kw (en millones) distribuidos de la Planta 1 a Guadalajara
+ $x_2$: Kw (en millones) distribuidos de la Planta 1 a León
+ $x_3$: Kw (en millones) distribuidos de la Planta 1 a Morelia
+ $x_4$: Kw (en millones) distribuidos de la Planta 2 a Guadalajara
+ $x_5$: Kw (en millones) distribuidos de la Planta 2 a León
+ $x_6$: Kw (en millones) distribuidos de la Planta 2 a Morelia
+ $x_7$: Kw (en millones) distribuidos de la Planta 3 a Guadalajara
+ $x_8$: Kw (en millones) distribuidos de la Planta 3 a León
+ $x_9$: Kw (en millones) distribuidos de la Planta 3 a Morelia

La tarea consiste en plantear el problema de programación lineal que permita satisfacer las necesidades de todas las ciudades al tiempo que minimice los costos asociados a la distribución y resolverlo con `linprog`.



In [141]:
# Matrices y cotas
c = np.array([5,2,7,3,6,6,6,1,2])

A_ineq = np.array([[1,1,1,0,0,0,0,0,0],
                  [0,0,0,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,1,1],
                  [-1,-1,-1,0,0,0,0,0,0],
                  [0,0,0,-1,-1,-1,0,0,0],
                  [0,0,0,0,0,0,-1,-1,-1]])

b_ineq = np.array([80,40,60,-70,-40,-70])

# bnds = ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None))
bnds = ((0, None),)*9

In [142]:
sol  = opt.linprog(c=c, A_ub=A_ineq, b_ub=b_ineq, bounds=bnds)
sol

     con: array([], dtype=float64)
     fun: 134.83932195390307
 message: 'The algorithm terminated successfully and determined that the problem is infeasible.'
     nit: 5
   slack: array([ 71.26798716,  34.36485206,  52.36663297, -61.26798716,
       -34.36485206, -62.36663297])
  status: 2
 success: False
       x: array([1.52797527, 0.0645337 , 7.13950387, 0.47769044, 2.57872875,
       2.57872875, 7.36633551, 0.01604137, 0.25099015])

In [143]:
opt.linprog(c=c, A_ub=A_ineq, b_ub=b_ineq)

     con: array([], dtype=float64)
     fun: 134.83932195390307
 message: 'The algorithm terminated successfully and determined that the problem is infeasible.'
     nit: 5
   slack: array([ 71.26798716,  34.36485206,  52.36663297, -61.26798716,
       -34.36485206, -62.36663297])
  status: 2
 success: False
       x: array([1.52797527, 0.0645337 , 7.13950387, 0.47769044, 2.57872875,
       2.57872875, 7.36633551, 0.01604137, 0.25099015])

In [144]:
x_min = sol.x
np.round(x_min)

array([2., 0., 7., 0., 3., 3., 7., 0., 0.])

In [145]:
c

array([5, 2, 7, 3, 6, 6, 6, 1, 2])

In [146]:
c.T.dot(x_min)

134.83932195390307